
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Josecarlos
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ANALIZADOR SINTACTICO");

        jTextField1.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resultado:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Analizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ingresar ejemplo 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ingresar ejemplo 2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Acerca del lenguaje");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)
                                    .addComponent(jButton2))
                                .addGap(25, 25, 25))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(36, 36, 36)
                        .addComponent(jButton4)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        DateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        System.out.println("INICANDO ANALISIS. Fecha: "+formatoFecha.format(fecha) 
                + " Hora: "+formatoHora.format(fecha));
        
        AnalizadorSintactico parser = new AnalizadorSintactico(jTextArea1.getText());
        int resultado = parser.hacerAnalisisSintactico();
        if(resultado == AnalizadorSintactico.ANALISIS_CORRECTO){
            jTextField1.setText("El analisis es correcto");
        }else if(resultado == AnalizadorSintactico.ERROR_LEXICO){
            jTextField1.setText("Existen errores lexicos. Linea: "+parser.ultimaLineaLeida());
        }else if(resultado == AnalizadorSintactico.ERROR_SINTACTICO){
            jTextField1.setText("Existen errores sintacticos. Linea: "+parser.ultimaLineaLeida());
        }
        
        fecha = new Date();
        System.out.println("FIN DE ANALISIS. Fecha: "+formatoFecha.format(fecha) 
                + " Hora: "+formatoHora.format(fecha));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String prueba = "public class Clase1  {\n" +
            "    String a =\"Esta es una cadena\";\n" +
            "    int y = 4;\n" +
            "    int x[3+2][a.length] = y + a.length + 2;\n" +
            "    bool flag = y > 3;\n" +
            "\n" +
            "    public int sumar(int sum1, int sum2){\n" +
            "        for(double c=4;c<sum1;c=c+sum2){\n" +
            "            if(c>20 | flag){\n" +
            "               y = true;\n" +
            "               System.out.print(\"Soy mayor a 20\");\n" +
            "            } else {\n" +
            "               y = false;\n" +
            "               c = 32;\n" +
            "            }\n" +
            "        }\n" +
            "        return a;\n" +
            "     }\n" +
            "}\n" +
            "private class Clase2 {\n" +
            "    Clase1 var = new Clase1();\n" +
            "    int a[3][2];\n" +
            "    double b = 3.11 + 32.22, otro = 2.34;\n" +
            "    String cad;\n" +
            "    \n" +
            "    public void hacerAlgo (int num1,double real1, String string1){\n" +
            "        Object ob = new Object();\n" +
            "        for(int i = 0; i < a.length, j < 3 ; i = i +1){\n" +
            "            for(int j = 0; j < a[i].length ; j = j +1){\n" +
            "                 a[i][j] = (num1 + i) + (j*2) + i / j - a[i][0];\n" +
            "            }\n" +
            "        }\n" +
            "        b = real1;\n" +
            "        cad = strin1 + b + var.toString().length;\n" +
            "        metodo();\n" +
            "     }\n" +
            "\n" +
            "     public void metodo(){\n" +
            "          /*Insertando un comentario AQUI!!! XD */\n" +
            "          b = b * 32 + (13 + 2) - var.sumar(45,32);\n" +
            "     }\n" +
            "}";
        jTextArea1.setText(prueba);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String prueba = "public class Clase1 {\n" +
            "    String cadena1 = \"Mi cadena\" + \" es \" + \" larga \";\n" +
            "    int entero1 = cadena1.length + 5;\n" +
            "    char caracter = 'F';\n    boolean bol = true;" +
            "    \n" +
            "    private void miMetodo(int numero){\n" +
            "        System.out.println(\"Este es mi numero: \" + numero);\n" +
            "        numero = numero * 2 + Character.hashCode(caracter);\n" +
            "    }\n" +
            "    \n" +
            "    public char otroMetodo(char c){\n" +
            "        if(Character.isDigit(c)){\n" +
            "            return cadena.charAt(3);\n" +
            "        }else if(c == 'A'){\n" +
            "            return 'A';\n" +
            "        }else if(c=='P'){\n" +
            "            return 'P';\n" +
            "        }\n" +
            "        return 'F';\n" +
            "    }\n" +
            "    \n" +
            "    public int getEntero1(){\n" +
            "        return entero1;\n" +
            "    }\n" +
            "}\n" +
            "\n" +
            "private class Clase2{\n" +
            "    double numReal = 200.34;\n" +
            "    int num1 = numReal * 10 + ( 23 * 2 / ( 45 - 10 ) ) ;\n" +
            "    Clase1 instancia = new Clase1();\n" +
            "    \n" +
            "    public int metodo(int a, int b, char car, String cad, Clase1 m){\n" +
            "        do{\n" +
            "            a = m.getEntero1() + a;\n" +
            "            b = (((b * 2)));\n" +
            "        } while (a > b);\n" +
            "        return a + b;\n" +
            "    }\n" +
            "}";
        jTextArea1.setText(prueba);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String mensaje = "* La gramatica del lenguaje es similar a Java. Con las excepciones:\n"
                + "+ La declaracion de arrays se da de la forma: 'int a[3], b[3]; "
                + "  NO DE LA FORMA: int[] d;\n"
                + "+ La operacion booleana AND se da con el simbolo &. NO CON: &&\n"
                + "+ La operacion booleana OR se da con el simbolo |. NO CON: ||\n"
                + "+ La declaracion de los atributos de una clase no acepta la forma:"
                + " public int x;\nSolo se acepta: int x; Sin embargo, los metodos deben "
                + "declararse de la forma: private void x(){}";
        
        JOptionPane.showMessageDialog(this, mensaje, "Acerca del lenguaje",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
